# Generated by Django 2.2 on 2021-11-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='U_id',
            field=models.IntegerField(default='15033', primary_key=True, serialize=False),
        ),
    ]
