# Generated by Django 2.2 on 2021-11-14 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0003_auto_20211114_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='CreateAt',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='U_id',
            field=models.IntegerField(default='36119', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='UpdateAt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
