# Generated by Django 2.2 on 2021-11-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0004_auto_20211114_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='U_id',
            field=models.IntegerField(default='99715', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='Fb_content',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='Fb_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
