# Generated by Django 2.2 on 2021-11-17 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0005_auto_20211115_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('import_price', models.IntegerField(default=0)),
                ('supplier', models.CharField(default='', max_length=50)),
                ('UpdateAt', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='U_id',
            field=models.IntegerField(default='61083', primary_key=True, serialize=False),
        ),
    ]
